-- ============================================
-- PHASE 06: DIGITAL RECEIPTS
-- ============================================
-- Stores payment receipt records for residents.
-- Auto-generated by webhook after payment_intent.succeeded.

CREATE TABLE IF NOT EXISTS receipts (
  id UUID PRIMARY KEY DEFAULT generate_uuid_v7(),
  community_id UUID NOT NULL REFERENCES communities(id),
  unit_id UUID NOT NULL REFERENCES units(id),
  resident_id UUID REFERENCES residents(id),
  transaction_id UUID REFERENCES transactions(id),
  stripe_payment_intent_id TEXT,
  receipt_number TEXT NOT NULL,
  amount NUMERIC(15, 2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'MXN',
  payment_method TEXT NOT NULL, -- 'card', 'oxxo', 'transfer', 'cash'
  description TEXT NOT NULL,
  payment_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT uq_receipt_transaction UNIQUE (transaction_id)
);

CREATE INDEX idx_receipts_unit ON receipts (unit_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_receipts_community ON receipts (community_id, created_at DESC) WHERE deleted_at IS NULL;

COMMENT ON TABLE receipts IS
  'Payment receipt records for residents. Auto-generated after successful payments.
   UNIQUE on transaction_id prevents duplicate receipts.';

-- ============================================
-- RLS POLICIES
-- ============================================

ALTER TABLE receipts ENABLE ROW LEVEL SECURITY;

-- Residents can view their own receipts (via occupancy)
CREATE POLICY "receipts_select_resident"
  ON receipts FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM occupancies o
      JOIN residents r ON r.id = o.resident_id
      WHERE o.unit_id = receipts.unit_id
        AND r.user_id = auth.uid()
        AND o.status = 'active'
        AND o.deleted_at IS NULL
        AND r.deleted_at IS NULL
    )
  );

-- Admins can view all receipts in their community
CREATE POLICY "receipts_select_admin"
  ON receipts FOR SELECT
  USING (
    community_id = (auth.jwt() -> 'app_metadata' ->> 'community_id')::UUID
    AND (auth.jwt() -> 'app_metadata' ->> 'role') IN ('super_admin', 'community_admin', 'manager')
  );

-- Service role inserts (from webhook Edge Function)
-- No client INSERT policy needed

-- ============================================
-- GENERATE RECEIPT NUMBER
-- ============================================

CREATE OR REPLACE FUNCTION generate_receipt_number(
  p_community_id UUID,
  p_date DATE DEFAULT CURRENT_DATE
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_year TEXT;
  v_sequence INTEGER;
BEGIN
  v_year := TO_CHAR(p_date, 'YYYY');

  SELECT COALESCE(
    MAX(
      NULLIF(
        REGEXP_REPLACE(receipt_number, '^REC-' || v_year || '-', ''),
        receipt_number
      )::INTEGER
    ),
    0
  ) + 1
  INTO v_sequence
  FROM public.receipts
  WHERE community_id = p_community_id
    AND receipt_number LIKE 'REC-' || v_year || '-%';

  RETURN 'REC-' || v_year || '-' || LPAD(v_sequence::TEXT, 5, '0');
END;
$$;

COMMENT ON FUNCTION generate_receipt_number IS
  'Generates sequential receipt numbers. Format: REC-YYYY-NNNNN.';
